package com.travelbird.trip.service;

import com.travelbird.file.entity.*;
import com.travelbird.file.repository.FileMetadataRepository;
import com.travelbird.file.storage.ObjectStorage;
import com.travelbird.global.error.*;
import com.travelbird.place.repository.PlaceRepository;
import com.travelbird.region.repository.SigunguMasterRepository;
import com.travelbird.trip.dto.request.*;
import com.travelbird.trip.dto.response.*;
import com.travelbird.trip.entity.*;
import com.travelbird.trip.mapper.TripMapper;
import com.travelbird.trip.repository.*;
import com.travelbird.trip.repository.querydsl.TripQueryRepository;
import com.travelbird.trip.repository.querydsl.TripWishlistQueryRepository;
import org.springframework.dao.DataIntegrityViolationException;
import com.travelbird.user.repository.UserRepository;
import java.time.*;
import java.util.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class TripService {
 private final TripRepository trips; private final TripWishlistRepository wishlist; private final PlaceRepository places; private final UserRepository users; private final SigunguMasterRepository regions; private final Clock clock; private TripPlaceRepository tripPlaces; private FileMetadataRepository files; private TripQueryRepository query; private TripWishlistQueryRepository wishlistQuery; private TripMapper mapper; private ObjectStorage storage;
 public TripService(TripRepository t,TripWishlistRepository w,PlaceRepository p,UserRepository u,SigunguMasterRepository r,Clock c){trips=t;wishlist=w;places=p;users=u;regions=r;clock=c;}
 @Autowired public TripService(TripRepository t,TripWishlistRepository w,PlaceRepository p,UserRepository u,SigunguMasterRepository r,Clock c,TripPlaceRepository tp,FileMetadataRepository f,TripQueryRepository q,TripWishlistQueryRepository wq,TripMapper m,ObjectStorage s){this(t,w,p,u,r,c);tripPlaces=tp;files=f;query=q;wishlistQuery=wq;mapper=m;storage=s;}
 @Transactional public CreateTripResponse createResponse(Long uid,CreateTripRequest r){return mapper.created(create(uid,r),today());}
 @Transactional public Trip create(Long userId,CreateTripRequest r){if(r==null)throw new BusinessException(ErrorCode.INVALID_REQUEST);if(r.startDate()==null||r.endDate()==null)throw new BusinessException(ErrorCode.TRIP_DATE_REQUIRED);if(r.regionCode()==null||!r.regionCode().matches("^[0-9]{5}$"))throw new BusinessException(ErrorCode.REGION_REQUIRED);if(r.companionType()==null)throw new BusinessException(ErrorCode.INVALID_COMPANION_TYPE);if(r.pace()==null)throw new BusinessException(ErrorCode.INVALID_TRIP_PACE);var validatedThemes=TripRequestPolicy.validatedThemes(r.themes());var user=users.findById(userId).orElseThrow(()->new BusinessException(ErrorCode.USER_NOT_FOUND));var region=regions.findBySigunguCode(r.regionCode()).orElseThrow(()->new BusinessException(ErrorCode.REGION_REQUIRED));return trips.save(Trip.createManual(user,region,r.startDate(),r.endDate(),r.companionType(),validatedThemes,r.pace(),LocalDateTime.now(clock)));}
 @Transactional(readOnly=true) public TripResponse detail(Long viewerId,Long id){var t=trips.findById(id).orElseThrow(()->new BusinessException(ErrorCode.TRIP_NOT_FOUND));if(t.getVisibility()==Visibility.PRIVATE&&!t.ownedBy(viewerId))throw new BusinessException(ErrorCode.TRIP_NOT_FOUND);return mapper.detail(t,viewerId,trips.findPublishedPostId(id).orElse(null),today());}
 @Transactional public TripResponse update(Long uid,Long id,UpdateTripRequest r){var t=ownedForUpdate(id,uid);t.ensureMutable();if(r==null||r.hasInvalidRequiredFields())throw new BusinessException(ErrorCode.INVALID_REQUEST);if(r.version()!=t.getVersion())throw new BusinessException(ErrorCode.TRIP_MODIFICATION_CONFLICT);if(r.routeChange()&&trips.existsPublishedPost(id))throw new BusinessException(ErrorCode.TRIP_ROUTE_LOCKED_BY_PUBLISHED_POST);t.updateBasic(r.title(),r.titlePresent(),r.summary(),r.summaryPresent(),r.companionType(),r.companionPresent(),r.themesPresent()?TripRequestPolicy.validatedPatchThemes(r.themes()):null,r.themesPresent(),r.pace(),r.pacePresent(),r.visibility(),r.visibilityPresent());if(r.routeChange()){var region=r.regionPresent()?regions.findBySigunguCode(r.regionCode()).orElseThrow(()->new BusinessException(ErrorCode.REGION_REQUIRED)):t.getRegion();var start=r.startPresent()?required(r.startDate()):t.getStartDate();var end=r.endPresent()?required(r.endDate()):t.getEndDate();if(end.isBefore(start))throw new BusinessException(ErrorCode.INVALID_TRIP_PERIOD);int wanted=(int)(java.time.temporal.ChronoUnit.DAYS.between(start,end)+1);var removedFiles=wanted<t.getDays().size()?t.getDays().subList(wanted,t.getDays().size()).stream().flatMap(d->d.getPlaces().stream()).flatMap(p->p.getImages().stream()).map(TripPlaceImage::getFile).toList():List.<FileMetadata>of();if(wanted<t.getDays().size()&&!Boolean.TRUE.equals(r.confirmDayRemoval())){var removed=t.getDays().subList(wanted,t.getDays().size()).stream().filter(d->!d.getPlaces().isEmpty()).map(d->Map.<String,Object>of("dayNumber",d.getDayNumber(),"placeIds",d.getPlaces().stream().map(p->p.getPlace().getId()).toList())).toList();if(!removed.isEmpty())throw new BusinessException(ErrorCode.TRIP_DAY_REMOVAL_CONFIRMATION_REQUIRED,ErrorCode.TRIP_DAY_REMOVAL_CONFIRMATION_REQUIRED.defaultMessage(),Map.of("removedDays",removed));}t.updateRoute(region,start,end,true);trips.flush();deleteFiles(removedFiles);}return mapper.detail(t,uid,trips.findPublishedPostId(id).orElse(null),today());}
 @Transactional public void addPlace(Long userId,Long tripId,int dayNumber,AddTripPlaceRequest r){var trip=ownedForUpdate(tripId,userId);trip.ensureMutable();routeUnlocked(tripId);var place=places.findById(r.placeId()).orElseThrow(()->new BusinessException(ErrorCode.PLACE_NOT_FOUND));try{int before=trip.day(dayNumber).getPlaces().size();int normalizedOrder=r.order()==null?before+1:Math.max(1,Math.min(r.order(),before+1));var added=trip.addPlace(dayNumber,place,r.placeId(),null);wishlist.deleteByTripIdAndPlaceId(tripId,r.placeId());trips.flush();if(normalizedOrder!=before+1){var ids=tripPlaces.findAllByTripIdAndDayDayNumberOrderByVisitOrder(tripId,dayNumber).stream().map(TripPlace::getId).collect(java.util.stream.Collectors.toCollection(ArrayList::new));ids.remove(added.getId());ids.add(normalizedOrder-1,added.getId());tripPlaces.stageOrders(tripId,dayNumber);for(int i=0;i<ids.size();i++)tripPlaces.setOrder(tripId,dayNumber,ids.get(i),i+1);}}catch(DataIntegrityViolationException e){throw new BusinessException(ErrorCode.PLACE_ALREADY_ADDED);}}
 @Transactional public void removePlace(Long uid,Long id,int day,Long tripPlaceId){var t=ownedForUpdate(id,uid);t.ensureMutable();routeUnlocked(id);var p=tripPlaces.findByIdAndTripId(tripPlaceId,id).orElseThrow(()->new BusinessException(ErrorCode.PLACE_NOT_FOUND));if(p.getDay().getDayNumber()!=day)throw new BusinessException(ErrorCode.PLACE_NOT_FOUND);var removed=p.getImages().stream().map(TripPlaceImage::getFile).toList();t.removePlace(day,tripPlaceId);trips.flush();var remaining=tripPlaces.findAllByTripIdAndDayDayNumberOrderByVisitOrder(id,day);tripPlaces.stageOrders(id,day);for(int i=0;i<remaining.size();i++)tripPlaces.setOrder(id,day,remaining.get(i).getId(),i+1);deleteFiles(removed);}
 @Transactional public void reorder(Long uid,Long id,int day,ReorderTripPlacesRequest r){var t=ownedForUpdate(id,uid);t.ensureMutable();routeUnlocked(id);var current=tripPlaces.findAllByTripIdAndDayDayNumberOrderByVisitOrder(id,day);if(r.orderedTripPlaceIds()==null||r.orderedTripPlaceIds().size()!=current.size()||new HashSet<>(r.orderedTripPlaceIds()).size()!=current.size())throw new BusinessException(ErrorCode.INVALID_PLACE_ORDER_REQUEST);var expected=current.stream().map(TripPlace::getId).collect(java.util.stream.Collectors.toSet());if(!expected.equals(new HashSet<>(r.orderedTripPlaceIds())))throw new BusinessException(ErrorCode.TRIP_PLACE_DAY_MISMATCH);tripPlaces.stageOrders(id,day);for(int i=0;i<r.orderedTripPlaceIds().size();i++)tripPlaces.setOrder(id,day,r.orderedTripPlaceIds().get(i),i+1);}
 @Transactional public void updateContent(Long uid,Long id,Long tripPlaceId,UpdateTripPlaceContentRequest r){var t=ownedForUpdate(id,uid);t.ensureMutable();var p=tripPlaces.findByIdAndTripId(tripPlaceId,id).orElseThrow(()->new BusinessException(ErrorCode.PLACE_NOT_FOUND));String memo=r.memoPresent()?r.memo():p.getMemo();if(memo!=null&&memo.length()>100)throw new BusinessException(ErrorCode.TRIP_PLACE_MEMO_TOO_LONG);var previous=p.getImages().stream().map(TripPlaceImage::getFile).toList();List<FileMetadata> images=r.imagesPresent()?loadImages(uid,r.imageFileIds()):previous;p.updateContent(memo,images);for(var f:images)f.link();tripPlaces.flush();deleteFiles(previous.stream().filter(f->!images.contains(f)).toList());}
 @Transactional public void addWishlist(Long uid,Long id,WishlistPlaceRequest r){var t=ownedForUpdate(id,uid);t.ensureMutable();if(wishlist.existsByTripIdAndPlaceId(id,r.placeId()))return;var p=places.findById(r.placeId()).orElseThrow(()->new BusinessException(ErrorCode.PLACE_NOT_FOUND));t.addWishlistPlace(r.placeId());try{wishlist.saveAndFlush(TripWishlistPlace.create(t,p,LocalDateTime.now(clock)));}catch(DataIntegrityViolationException e){if(t.getDays().stream().flatMap(d->d.getPlaces().stream()).anyMatch(tp->Objects.equals(tp.getPlace().getId(),r.placeId())))throw new BusinessException(ErrorCode.PLACE_ALREADY_ASSIGNED_TO_DAY);}}
 @Transactional(readOnly=true) public WishlistPlaceListResponse wishlist(Long uid,Long id,Long cursor,Integer size){owned(id,uid);int n=size(size);var rows=wishlistQuery.findPage(id,cursor,n+1);boolean more=rows.size()>n;var page=more?rows.subList(0,n):rows;var items=page.stream().map(w->new WishlistPlaceItem(w.getPlace().getId(),w.getPlace().getName(),w.getPlace().getCategory(),w.getPlace().getAddress(),w.getPlace().getImageUrl(),w.getAddedAt(),Objects.requireNonNullElse(w.getPlace().getDescription(),""))).toList();return new WishlistPlaceListResponse(items,more?page.get(page.size()-1).getPlace().getId():null);}
 @Transactional public void removeWishlist(Long uid,Long id,Long placeId){var t=ownedForUpdate(id,uid);t.ensureMutable();wishlist.deleteByTripIdAndPlaceId(id,placeId);}
 @Transactional(readOnly=true) public TripListResponse list(Long uid,TripStatus status,Long cursor,Integer size){TripListPolicy.validate(status);int n=size(size);var rows=query.list(uid,status,cursor,n+1,today());boolean more=rows.size()>n;var page=more?rows.subList(0,n):rows;return new TripListResponse(page.stream().map(t->mapper.list(t,today())).toList(),more?page.get(page.size()-1).getId():null);}
 @Transactional(readOnly=true) public TravelCalendarResponse calendar(Long uid,LocalDate from,LocalDate to){if(from==null||to==null||to.isBefore(from))throw new BusinessException(ErrorCode.INVALID_DATE_RANGE);return new TravelCalendarResponse(query.calendar(uid,from,to).stream().map(t->mapper.calendar(t,today())).toList());}
 @Transactional(readOnly=true) public RouteResponse route(Long viewer,Long id,int day){var t=trips.findById(id).orElseThrow(()->new BusinessException(ErrorCode.TRIP_NOT_FOUND));if(t.getVisibility()==Visibility.PRIVATE&&!t.ownedBy(viewer))throw new BusinessException(ErrorCode.TRIP_NOT_FOUND);return mapper.route(t,t.day(day));}
 @Transactional public void cancel(Long userId,Long tripId){var trip=ownedForUpdate(tripId,userId);if(trip.getCancelledAt()!=null)return;trips.findPublishedPostId(tripId).ifPresent(postId->{throw new BusinessException(ErrorCode.TRIP_CANCEL_REQUIRES_POST_DELETION,ErrorCode.TRIP_CANCEL_REQUIRES_POST_DELETION.defaultMessage(),Map.of("postId",postId));});trip.cancel(LocalDateTime.now(clock));}
 private List<FileMetadata> loadImages(Long uid,List<Long> ids){TripImagePolicy.validateFileIds(ids);if(ids.size()>3)throw new BusinessException(ErrorCode.TRIP_PLACE_IMAGE_LIMIT_EXCEEDED);if(new HashSet<>(ids).size()!=ids.size())throw new BusinessException(ErrorCode.INVALID_REQUEST);var result=new ArrayList<FileMetadata>();for(Long id:ids){var f=files.findById(id).orElseThrow(()->new BusinessException(ErrorCode.FILE_ACCESS_DENIED));if(!f.isOwnedBy(uid)||!f.isCompleted()||f.getPurpose()!=FilePurpose.TRIP_PLACE)throw new BusinessException(ErrorCode.FILE_ACCESS_DENIED);result.add(f);}return result;}
 private void deleteFiles(List<FileMetadata> removed){for(var f:removed){storage.delete(f.objectKey());files.delete(f);}}
 private void routeUnlocked(Long id){if(trips.existsPublishedPost(id))throw new BusinessException(ErrorCode.TRIP_ROUTE_LOCKED_BY_PUBLISHED_POST);} private LocalDate today(){return LocalDate.now(clock.withZone(ZoneId.of("Asia/Seoul")));} private int size(Integer s){int n=s==null?20:s;if(n<1||n>50)throw new BusinessException(ErrorCode.INVALID_REQUEST);return n;} private <T>T required(T value){if(value==null)throw new BusinessException(ErrorCode.INVALID_REQUEST);return value;}
 private Trip owned(Long id,Long uid){var t=trips.findById(id).orElseThrow(()->new BusinessException(ErrorCode.TRIP_NOT_FOUND));if(!t.ownedBy(uid))throw new BusinessException(ErrorCode.TRIP_ACCESS_DENIED);return t;} private Trip ownedForUpdate(Long id,Long uid){var t=trips.findByIdForUpdate(id).orElseThrow(()->new BusinessException(ErrorCode.TRIP_NOT_FOUND));if(!t.ownedBy(uid))throw new BusinessException(ErrorCode.TRIP_ACCESS_DENIED);return t;}
}