package com.travelbird.ai.service;
import com.travelbird.ai.client.*;import com.travelbird.global.error.*;import java.util.concurrent.ConcurrentHashMap;import org.springframework.scheduling.annotation.Async;import org.springframework.stereotype.Component;import org.springframework.transaction.event.*;
@Component public class AiRecommendationDispatcher{
 private final AiRecommendationClient client;private final AiJobTransitionService transitions;private final ConcurrentHashMap<Long,Object> locks=new ConcurrentHashMap<>();public AiRecommendationDispatcher(AiRecommendationClient c,AiJobTransitionService t){client=c;transitions=t;}
 @Async @TransactionalEventListener(phase=TransactionPhase.AFTER_COMMIT)public void dispatch(AiDispatchRequested event){dispatchSafely(event);}
 public void dispatchSafely(AiDispatchRequested event){Object lock=locks.computeIfAbsent(event.request().jobId(),ignored->new Object());try{synchronized(lock){dispatchOnce(event);}}catch(BusinessException e){if(e.errorCode()==ErrorCode.AI_JOB_ID_CONFLICT){transitions.failed(event.request().jobId(),AiJobFailureCode.AI_JOB_ID_CONFLICT,e.getMessage(),false);}else{transitions.failed(event.request().jobId(),AiJobFailureCode.AI_SERVICE_UNAVAILABLE,"Unexpected AI dispatch failure",true);}}catch(RuntimeException e){transitions.failed(event.request().jobId(),AiJobFailureCode.AI_SERVICE_UNAVAILABLE,"Unexpected AI dispatch failure",true);}finally{locks.remove(event.request().jobId(),lock);}}
 void dispatchOnce(AiDispatchRequested event){if(!transitions.prepare(event.request().jobId(),event.fingerprint()))return;try{if(!event.syncRequest().places().isEmpty())client.sync(event.syncRequest());}catch(AiClientException e){transitions.failed(event.request().jobId(),AiJobFailureCode.AI_PLACE_SYNC_FAILED,e.getMessage(),true);return;}try{client.recommend(event.request());transitions.processing(event.request().jobId());}catch(AiClientException e){transitions.failed(event.request().jobId(),failure(e.errorCode()),e.getMessage(),e.errorCode()==ErrorCode.AI_SERVICE_UNAVAILABLE);}}
 private AiJobFailureCode failure(ErrorCode c){try{return AiJobFailureCode.valueOf(c.name());}catch(IllegalArgumentException e){return AiJobFailureCode.AI_SERVICE_UNAVAILABLE;}}
}
