package com.travelbird.ai.client;
import com.fasterxml.jackson.databind.ObjectMapper;import com.travelbird.ai.dto.internal.*;import com.travelbird.global.error.ErrorCode;import java.nio.charset.StandardCharsets;import java.util.Objects;import org.springframework.http.*;import org.springframework.web.client.RestClient;
public class HttpAiRecommendationClient implements AiRecommendationClient{
 static final String INTERNAL_KEY_HEADER="X-Internal-AI-Key";private final RestClient client;private final String key;private final ObjectMapper json;
 public HttpAiRecommendationClient(RestClient c,String k){this(c,k,new ObjectMapper().findAndRegisterModules());}public HttpAiRecommendationClient(RestClient c,String k,ObjectMapper j){client=c;key=k;json=j;}
 public void sync(PlaceSyncRequest r){exchange("/internal/v1/places/sync",r,HttpStatus.NO_CONTENT,Void.class);}
 public AiServerAcceptedResponse recommend(RecommendationJobRequest r){var a=exchange("/internal/v1/recommendations",r,HttpStatus.ACCEPTED,AiServerAcceptedResponse.class);if(a==null||!Objects.equals(r.jobId(),a.jobId())||!"PENDING".equals(a.status())||a.acceptedAt()==null)throw new AiClientException(ErrorCode.AI_SERVICE_UNAVAILABLE,"AI accepted response violates contract",null);return a;}
 private <T>T exchange(String path,Object body,HttpStatus expected,Class<T> type){try{return client.method(path.endsWith("sync")?HttpMethod.PUT:HttpMethod.POST).uri(path).header(INTERNAL_KEY_HEADER,key).body(body).exchange((q,r)->{if(r.getStatusCode().value()!=expected.value()){String b=new String(r.getBody().readAllBytes(),StandardCharsets.UTF_8);throw remote(r.getStatusCode().value(),b);}return type==Void.class?null:r.bodyTo(type);});}catch(AiClientException e){throw e;}catch(RuntimeException e){throw new AiClientException(ErrorCode.AI_SERVICE_UNAVAILABLE,"AI service unavailable",e);}}
 private AiClientException remote(int status,String body){ErrorCode code=ErrorCode.AI_SERVICE_UNAVAILABLE;try{code=ErrorCode.valueOf(json.readTree(body).path("code").asText());}catch(Exception ignored){}if((status==400&&code!=ErrorCode.INVALID_REQUEST)||(status==401&&code!=ErrorCode.INVALID_INTERNAL_AI_KEY)||(status==409&&code!=ErrorCode.AI_JOB_ID_CONFLICT)||(status==422&&code!=ErrorCode.PLACE_NOT_FOUND&&code!=ErrorCode.PLACE_REGION_MISMATCH&&code!=ErrorCode.CONFLICTING_PLACE_POLICY))code=ErrorCode.AI_SERVICE_UNAVAILABLE;return new AiClientException(code,"AI request rejected with HTTP "+status,null);}
}
